### ISSUE TITLE
What does this line do?

### ISSUE THREAD

**Issue by jrd656** [WebAhead5/Tamagotchi#20]
const handleChangeTime = event => setTimeToDeath(timeToDeath +5 % 30 > 30? 30:timeToDeath +5);

I can't understand the maths behind it? It's line 8 on App.js

**Comment by amirfahoum** [comment]
on the start  the time death start with=30 ,  every time the user click a button it add 5 to the time to death, in this line we checked if the new value>30 so return 30, if its not  we return newval..
